### ISSUE TITLE
[MC 1.7.10] NoSuchMethodError in utils.NameCollector.tryAddPlayer()

### ISSUE THREAD

**Issue by Kasran** [OpenMods/OpenData#13]
http://openeye.openmods.info/crashes/20d17fd2f11612fbb605d4e41a18b647 among others. It looks like it's trying to use some method from Minecraft's auth stuff that isn't implemented anymore, or something (this isn't really my field of expertise). I'd be less bothered if OpenEye weren't [listed on the MCF Mod List as working with 1.7.10](http://modlist.mcf.li/version/1.7.10#openeye).
